### ISSUE TITLE
Intel Macs please!

### ISSUE THREAD

**Issue by fire17** [VasylBaran/CommandShift#14]
Hi there, hope you're well :)
Got my friends old computer, 2014 mac with intel (bigsur)
and would realy like to switch languages with the muscle memory i have

please support intel macs please!
not sure why the cpu is relevant to language changes
i guess ill try the dmg and see if it works or not haha

all the best

**Comment by VasylBaran** [comment]
hi @fire17! Try this release: https://github.com/VasylBaran/CommandShift/releases/tag/1.01

Choose Intel version. If you have problems - let me know

**Comment by fire17** [comment]
thanks @VasylBaran ! im happy i wrote you!
it's working though there is not interface, so i wonder if it will start automatically when the computer has turned on
or i have to remember to open it...

Also, it only switches from the last 2 languages...
If I have 3 or more, i must use the os native to switch
have you found a solution to 3+ langs?
can we remap Command+Shift to be the working os multi-lang one?

Thanks a lot and all the best !

**Comment by VasylBaran** [comment]
@fire17 I'm happy to hear that it works for you =)

Here I describe how to make CommandShift start when your system boots: https://github.com/VasylBaran/CommandShift?tab=readme-ov-file#faq
but basically: 

> You can add CommandShift to your list of auto-start items by opening System Settings panel -> Users and Groups OR General (depending on what version of macOS you're using) -> Login Items -> [+] -> [select CommandShift app]

**Comment by fire17** [comment]
Thanks will do!
Any ideas about the 3+ language switching ?

**Comment by VasylBaran** [comment]
@fire17 I just got it to work with a small workaround. 

Go to your system settings -> Keyboard shortcuts -> Input Sources and change shortcut for "Select **next source** in Input menu" to "⌃Space" and either disable or change shortcut for "Select **previous source** in Input menu" to something else (otherwise there would be a conflict of shortcuts)

It's a temporary workaround but it works. I plan to add a better (out-of-the-box) solution in the near future. Cheers! ;-)

**Comment by fire17** [comment]
Awesome!!!!! That worked! Thanks a lot!
It would be seamless if it also showed the HUD change like the native does, but that's extra

I finally have a Alt Shift or (command shift) working with multilang!
Thanks ALOT and all the best!!

**Comment by VasylBaran** [comment]
I'm glad to hear that you also found it useful. 

When I switched to Mac for the first time I was annoyed when I realized that I can't use Alt+Shift to switch between languages so I wrote this small app. Then a friend of mine bought his first Mac and asked me how to switch between languages with Alt+Shift and I explained that you can't do it natively and I had to write a small app for it to work. He asked me to share it and so I decided to also share it here on GitHub in case other people find it useful.

I will add this workaround hack to the FAQ section, thanks for a good suggestion.

> It would be seamless if it also showed the HUD change like the native does, but that's extra

what do you mean by "showed the HUD change" ?

**Comment by fire17** [comment]
> showed the HUD change

it doesnt work now for me anymore but i used to see something like this (has light and dark mode)
![image](https://github.com/VasylBaran/CommandShift/assets/9356048/7f3c48cb-a154-4073-979e-62c4d3f56338)
![image](https://github.com/VasylBaran/CommandShift/assets/9356048/0eac7c56-34fc-4f66-aaf4-d84054f71b2e)
(images found online)

it would be nice if theres was an option to toggle seeing it or not (from the drop menu)

Gonna close this issue as you indeed solved my original request! (if you manage to add the hud it will be a nice bonus)
PS - ur a legend for adding the github page to the drop menu... it was right there when i wanted it ❤️ 
All the best!

**Comment by VasylBaran** [comment]
@fire17 hi there! Please check the latest release: https://github.com/VasylBaran/CommandShift/releases/tag/1.03

* I've added a toggle to change language AFTER Shift release
* Made it possible to switch languages using just Shift 
* Made it possible to choose whether you would like to hide tray icon from the menu permanently or until restart 

Now I can also see 'HUD change' if I press down and hold the second key (the one you chose from the "Change language with..." drop-down) the then press Shift multiple times in order to cycle through your languages.

<img width="422" alt="Screenshot 2024-04-28 at 22 48 55" src="https://github.com/VasylBaran/CommandShift/assets/12252940/c1b0f2be-b210-474b-96c2-0226d3c490d1">
<img width="258" alt="Screenshot 2024-04-28 at 22 52 43" src="https://github.com/VasylBaran/CommandShift/assets/12252940/cd425874-6ceb-4527-aa87-66cd40f95e49">
